package hello.dcsms.omzen.theme;

import android.os.Environment;

public class ThemeKontsran {
	public static String OMZENTHEMEDIR = Environment
			.getExternalStorageDirectory() + "/OMZen/theme";
	public static String OMZENROOTDIR = Environment
			.getExternalStorageDirectory() + "/OMZen";
	public static String OMZENCACHEDIR = Environment
			.getExternalStorageDirectory() + "/OMZen/.cache";

	public static String NAMATEMA = "namatema";
	public static String PENGRAJIN = "pengrajin";
	public static String KETERANGAN = "keterangan";
	public static String VERSI = "versi";
	public static String KONTAK = "kontak";
	public static String[] BATRAI_ICON = new String[] { "stat_sys_battery_0",
			"stat_sys_battery_100", "stat_sys_battery_15",
			"stat_sys_battery_28", "stat_sys_battery_43 copy",
			"stat_sys_battery_43", "stat_sys_battery_57",
			"stat_sys_battery_71", "stat_sys_battery_85",
			"stat_sys_battery_charge_anim0", "stat_sys_battery_charge_anim100",
			"stat_sys_battery_charge_anim15", "stat_sys_battery_charge_anim28",
			"stat_sys_battery_charge_anim43", "stat_sys_battery_charge_anim57",
			"stat_sys_battery_charge_anim71", "stat_sys_battery_charge_anim85" };
	public static String[] SINYAL_ICON = new String[] { "sim1focus", "sim1n",
			"sim1null", "sim2focus", "sim2n", "sim2null", "sinyal0", "sinyal1",
			"sinyal2", "sinyal3", "sinyal4", "sinyalnet0", "sinyalnet1",
			"sinyalnet2", "sinyalnet3", "sinyalnet4" };
	public static String[] INOUT_ICON = new String[] {
			"stat_sys_data_connected_1x", "stat_sys_data_connected_3g",
			"stat_sys_data_connected_4g", "stat_sys_data_connected_d",
			"stat_sys_data_connected_e", "stat_sys_data_connected_g",
			"stat_sys_data_connected_h", "stat_sys_data_connected_hplus",
			"stat_sys_data_connected_lte", "stat_sys_data_connected_roam",
			"stat_sys_data_fully_connected_1x",
			"stat_sys_data_fully_connected_3g",
			"stat_sys_data_fully_connected_4g",
			"stat_sys_data_fully_connected_d",
			"stat_sys_data_fully_connected_e",
			"stat_sys_data_fully_connected_g",
			"stat_sys_data_fully_connected_h",
			"stat_sys_data_fully_connected_hplus",
			"stat_sys_data_fully_connected_lte",
			"stat_sys_data_fully_connected_roam", "stat_sys_signal_in",
			"stat_sys_signal_inout", "stat_sys_signal_inout_null",
			"stat_sys_signal_out" };
	public static String[] TOGGLE_ICON = new String[] {
			"asus_ep_statusicon_always_off", "asus_ep_statusicon_always_on",
			"asus_ep_statusicon_audio_wizard_off",
			"asus_ep_statusicon_audio_wizard_on",
			"asus_ep_statusicon_auto_rotate_off",
			"asus_ep_statusicon_auto_rotate_on",
			"asus_ep_statusicon_autosync_off",
			"asus_ep_statusicon_autosync_on",
			"asus_ep_statusicon_bluetooth_off",
			"asus_ep_statusicon_bluetooth_on",
			"asus_ep_statusicon_calculator_on", "asus_ep_statusicon_camera_on",
			"asus_ep_statusicon_clean", "asus_ep_statusicon_data_off",
			"asus_ep_statusicon_data_on", "asus_ep_statusicon_dictionary_off",
			"asus_ep_statusicon_dictionary_on",
			"asus_ep_statusicon_flashlight_off",
			"asus_ep_statusicon_flashlight_on",
			"asus_ep_statusicon_flightmode_off",
			"asus_ep_statusicon_flightmode_on",
			"asus_ep_statusicon_fmradio_on", "asus_ep_statusicon_gps_off",
			"asus_ep_statusicon_gps_on",
			"asus_ep_statusicon_miracast_setting_off",
			"asus_ep_statusicon_miracast_setting_on",
			"asus_ep_statusicon_nfc_off", "asus_ep_statusicon_nfc_on",
			"asus_ep_statusicon_pavingnew_off",
			"asus_ep_statusicon_pavingnew_on",
			"asus_ep_statusicon_quickmemo_on",
			"asus_ep_statusicon_reading_off", "asus_ep_statusicon_reading_on",
			"asus_ep_statusicon_silent", "asus_ep_statusicon_silent_off",
			"asus_ep_statusicon_sim1_off", "asus_ep_statusicon_sim1_on",
			"asus_ep_statusicon_sim2_off", "asus_ep_statusicon_sim2_on",
			"asus_ep_statusicon_sound", "asus_ep_statusicon_vibrate",
			"asus_ep_statusicon_voice_recorder_on",
			"asus_ep_statusicon_wifi_off", "asus_ep_statusicon_wifi_on",
			"asus_ep_statusicon_wifisharing_off",
			"asus_ep_statusicon_wifisharing_on", };
	public static String[] TOOGLEBG = new String[] { "toggle_btn_bg_mask",
			"toggle_btn_bg_n", "toggle_btn_bg_n_y", "toggle_btn_bg_off",
			"toggle_btn_bg_off_y", "toggle_btn_bg_on", "toggle_btn_bg_on_y",
			"toggle_btn_bg_top" };
	public static String[] NOTIFIMAGE = new String[] { "asus_brightness_bg.9",
			"asus_brightness_control_gray_bg.9",
			"asus_brightness_control_hl_bg.9", "asus_ep_btn_edit_hl",
			"asus_ep_btn_edit_n", "asus_ep_btn_list_hl", "asus_ep_btn_list_n",
			"asus_ep_btn_more_d.9", "asus_ep_btn_more_hl.9",
			"asus_ep_btn_more_n.9", "asus_ep_btn_quicksetting_hl",
			"asus_ep_btn_quicksetting_n", "asus_ep_btn_setting_hl",
			"asus_ep_btn_setting_n", "asus_ep_pulldown_bar",
			"asus_notification_header_background.9",
			"asus_notification_panel_background.9", "clear_button_disable.9",
			"clear_button_normal.9", "clear_button_press.9",
			"notification_bg.9", "notification_bg_low.9", "panel_bg.9",
			"panel_handle_bg.9" };
	public static String[] STATUSBAR_BG = new String[] { "statusbar_background.9" };
	public static String[] STATUSBAR_ICON = new String[] {
			"battery_low_battery", "com_bbm_notif_icon",
			"com_bbm_notif_icon_splat", "font_satu", "stat_notify_image",
			"stat_notify_image_error", "stat_notify_more", "stat_sys_alarm",
			"stat_sys_data_bluetooth", "stat_sys_data_bluetooth_connected",
			"stat_sys_gps_acquiring", "stat_sys_no_sim",
			"stat_sys_ringer_silent", "stat_sys_ringer_vibrate",
			"stat_sys_signal_flightmode", "stat_sys_sync",
			"stat_sys_sync_error", "stat_sys_tty_mode", "stat_sys_wifi_in",
			"stat_sys_wifi_inout", "stat_sys_wifi_inout_null",
			"stat_sys_wifi_out", "stat_sys_wifi_signal_0",
			"stat_sys_wifi_signal_1", "stat_sys_wifi_signal_1_fully",
			"stat_sys_wifi_signal_2", "stat_sys_wifi_signal_2_fully",
			"stat_sys_wifi_signal_3", "stat_sys_wifi_signal_3_fully",
			"stat_sys_wifi_signal_4", "stat_sys_wifi_signal_4_fully",
			"stat_sys_wifi_signal_null" };
	public static String[] ALLICONS = new String[] { "asus_brightness_bg.9",
			"asus_brightness_control_gray_bg.9",
			"asus_brightness_control_hl_bg.9", "asus_ep_btn_edit_hl",
			"asus_ep_btn_edit_n", "asus_ep_btn_list_hl", "asus_ep_btn_list_n",
			"asus_ep_btn_more_d.9", "asus_ep_btn_more_hl.9",
			"asus_ep_btn_more_n.9", "asus_ep_btn_quicksetting_hl",
			"asus_ep_btn_quicksetting_n", "asus_ep_btn_setting_hl",
			"asus_ep_btn_setting_n", "asus_ep_pulldown_bar",
			"asus_ep_statusicon_always_off", "asus_ep_statusicon_always_on",
			"asus_ep_statusicon_audio_wizard_off",
			"asus_ep_statusicon_audio_wizard_on",
			"asus_ep_statusicon_auto_rotate_off",
			"asus_ep_statusicon_auto_rotate_on",
			"asus_ep_statusicon_autosync_off",
			"asus_ep_statusicon_autosync_on",
			"asus_ep_statusicon_bluetooth_off",
			"asus_ep_statusicon_bluetooth_on",
			"asus_ep_statusicon_calculator_on", "asus_ep_statusicon_camera_on",
			"asus_ep_statusicon_clean", "asus_ep_statusicon_data_off",
			"asus_ep_statusicon_data_on", "asus_ep_statusicon_dictionary_off",
			"asus_ep_statusicon_dictionary_on",
			"asus_ep_statusicon_flashlight_off",
			"asus_ep_statusicon_flashlight_on",
			"asus_ep_statusicon_flightmode_off",
			"asus_ep_statusicon_flightmode_on",
			"asus_ep_statusicon_fmradio_on", "asus_ep_statusicon_gps_off",
			"asus_ep_statusicon_gps_on",
			"asus_ep_statusicon_miracast_setting_off",
			"asus_ep_statusicon_miracast_setting_on",
			"asus_ep_statusicon_nfc_off", "asus_ep_statusicon_nfc_on",
			"asus_ep_statusicon_pavingnew_off",
			"asus_ep_statusicon_pavingnew_on",
			"asus_ep_statusicon_quickmemo_on",
			"asus_ep_statusicon_reading_off", "asus_ep_statusicon_reading_on",
			"asus_ep_statusicon_silent", "asus_ep_statusicon_silent_off",
			"asus_ep_statusicon_sim1_off", "asus_ep_statusicon_sim1_on",
			"asus_ep_statusicon_sim2_off", "asus_ep_statusicon_sim2_on",
			"asus_ep_statusicon_sound", "asus_ep_statusicon_vibrate",
			"asus_ep_statusicon_voice_recorder_on",
			"asus_ep_statusicon_wifi_off", "asus_ep_statusicon_wifi_on",
			"asus_ep_statusicon_wifisharing_off",
			"asus_ep_statusicon_wifisharing_on",
			"asus_notification_header_background.9",
			"asus_notification_panel_background.9", "clear_button_disable.9",
			"clear_button_normal.9", "clear_button_press.9",
			"notification_bg.9", "notification_bg_low.9", "panel_bg.9",
			"panel_handle_bg.9", "statusbar_background.9",
			"toggle_btn_bg_mask", "toggle_btn_bg_n", "toggle_btn_bg_n_y",
			"toggle_btn_bg_off", "toggle_btn_bg_off_y", "toggle_btn_bg_on",
			"toggle_btn_bg_on_y", "toggle_btn_bg_top", "battery_low_battery",
			"com_bbm_notif_icon", "com_bbm_notif_icon_splat", "font_satu",
			"sim1focus", "sim1n", "sim1null", "sim2focus", "sim2n", "sim2null",
			"sinyal0", "sinyal1", "sinyal2", "sinyal3", "sinyal4",
			"sinyalnet0", "sinyalnet1", "sinyalnet2", "sinyalnet3",
			"sinyalnet4", "stat_notify_image", "stat_notify_image_error",
			"stat_notify_more", "stat_sys_alarm", "stat_sys_battery_0",
			"stat_sys_battery_100", "stat_sys_battery_15",
			"stat_sys_battery_28", "stat_sys_battery_43 copy",
			"stat_sys_battery_43", "stat_sys_battery_57",
			"stat_sys_battery_71", "stat_sys_battery_85",
			"stat_sys_battery_charge_anim0", "stat_sys_battery_charge_anim100",
			"stat_sys_battery_charge_anim15", "stat_sys_battery_charge_anim28",
			"stat_sys_battery_charge_anim43", "stat_sys_battery_charge_anim57",
			"stat_sys_battery_charge_anim71", "stat_sys_battery_charge_anim85",
			"stat_sys_data_bluetooth", "stat_sys_data_bluetooth_connected",
			"stat_sys_data_connected_1x", "stat_sys_data_connected_3g",
			"stat_sys_data_connected_4g", "stat_sys_data_connected_d",
			"stat_sys_data_connected_e", "stat_sys_data_connected_g",
			"stat_sys_data_connected_h", "stat_sys_data_connected_hplus",
			"stat_sys_data_connected_lte", "stat_sys_data_connected_roam",
			"stat_sys_data_fully_connected_1x",
			"stat_sys_data_fully_connected_3g",
			"stat_sys_data_fully_connected_4g",
			"stat_sys_data_fully_connected_d",
			"stat_sys_data_fully_connected_e",
			"stat_sys_data_fully_connected_g",
			"stat_sys_data_fully_connected_h",
			"stat_sys_data_fully_connected_hplus",
			"stat_sys_data_fully_connected_lte",
			"stat_sys_data_fully_connected_roam", "stat_sys_gps_acquiring",
			"stat_sys_no_sim", "stat_sys_ringer_silent",
			"stat_sys_ringer_vibrate", "stat_sys_signal_flightmode",
			"stat_sys_signal_in", "stat_sys_signal_inout",
			"stat_sys_signal_inout_null", "stat_sys_signal_out",
			"stat_sys_sync", "stat_sys_sync_error", "stat_sys_tty_mode",
			"stat_sys_wifi_in", "stat_sys_wifi_inout",
			"stat_sys_wifi_inout_null", "stat_sys_wifi_out",
			"stat_sys_wifi_signal_0", "stat_sys_wifi_signal_1",
			"stat_sys_wifi_signal_1_fully", "stat_sys_wifi_signal_2",
			"stat_sys_wifi_signal_2_fully", "stat_sys_wifi_signal_3",
			"stat_sys_wifi_signal_3_fully", "stat_sys_wifi_signal_4",
			"stat_sys_wifi_signal_4_fully", "stat_sys_wifi_signal_null" };

}
